[theme]
# Light theme configuration to force consistent styling
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"  # Pure white background
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

# Additional theme settings for consistency
base = "light"  # Force light base theme

# Custom CSS to ensure our overrides take precedence
[client]
# Enable custom CSS
showErrorDetails = true

[server]
# Server configuration
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser configuration
gatherUsageStats = false 